INSERT INTO games (title, description, release_date, image_url, version) VALUES
('Anno 1701 - Dawn of Discovery', 'A strategy game set in the Age of Discovery.', '2006-10-10', 'assets/images/games/anno-1701-dawn-of-discovery.jpg', '1.0'),
('Animal Crossing - Wild World', 'A life simulation game where players live in a village.', '2005-11-23', 'assets/images/games/animal-crossing-wild-world.jpg', '1.0'),
('Art Academy', 'An educational game that teaches art techniques.', '2009-06-12', 'assets/images/games/art-academy.jpg', '1.0'),
('Assassins Creed Altairs Chronicles', 'An action-adventure game set in the Assassins Creed universe.', '2008-02-05', 'assets/images/games/assassins-creed-altairs-chronicles.jpg', '1.0'),
('Assassins Creed 2 Discovery', 'A side-scrolling action-adventure game.', '2009-11-17', 'assets/images/games/assassins-creed-2-discovery.jpg', '1.0'),
('Asterix at the Olympic Games', 'A sports game based on the Asterix comic series.', '2008-01-25', 'assets/images/games/asterix-at-the-olympic-games.jpg', '1.0'),
('Asterix - Brain Trainer', 'A brain training game featuring Asterix characters.', '2009-03-20', 'assets/images/games/asterix-brain-trainer.jpg', '1.0'),
('Asterix - These Romans Are Crazy!', 'A platform game featuring Asterix and Obelix.', '2009-10-30', 'assets/images/games/asterix-these-romans-are-crazy.jpg', '1.0'),
('Asterix & Obelix XXL 2 - Mission Wifix', 'An action-adventure game featuring Asterix and Obelix.', '2010-10-15', 'assets/images/games/asterix-and-obelix-xxl-2-mission-wifix.jpg', '1.0'),
('Avatar - The Legend of Aang - The Burning Earth', 'An action-adventure game based on the Avatar series.', '2007-10-16', 'assets/images/games/avatar-the-legend-of-aang-the-burning-earth.jpg', '1.0'),
('Bakugan - Battle Brawlers', 'A fighting game based on the Bakugan franchise.', '2009-03-24', 'assets/images/games/bakugan-battle-brawlers.jpg', '1.0'),
('Bakugan - Battle Brawlers - Battle Trainer', 'A training game for Bakugan battles.', '2009-10-20', 'assets/images/games/bakugan-battle-brawlers-battle-trainer.jpg', '1.0'),
('Bakugan - Defenders of the Core', 'An action-adventure game set in the Bakugan universe.', '2010-03-23', 'assets/images/games/bakugan-defenders-of-the-core.jpg', '1.0'),
('Bakugan - Rise of the Resistance', 'A strategy game based on the Bakugan series.', '2010-10-12', 'assets/images/games/bakugan-rise-of-the-resistance.jpg', '1.0'),
('Batman - The Brave and the Bold - The Videogame', 'A beat-em-up game featuring Batman.', '2010-09-07', 'assets/images/games/batman-the-brave-and-the-bold-the-videogame.jpg', '1.0'),
('Ben 10 - Alien Force', 'An action-adventure game based on the Ben 10 series.', '2008-10-28', 'assets/images/games/ben-10-alien-force.jpg', '1.0'),
('Ben 10 - Alien Force - Vilgax Attacks', 'An action game featuring Ben 10.', '2009-10-06', 'assets/images/games/ben-10-alien-force-vilgax-attacks.jpg', '1.0'),
('Ben 10 - Galactic Racing', 'A racing game featuring characters from Ben 10.', '2011-10-11', 'assets/images/games/ben-10-galactic-racing.jpg', '1.0'),
('Ben 10 - Omniverse', 'An action-adventure game featuring Ben 10.', '2012-10-09', 'assets/images/games/ben-10-omniverse.jpg', '1.0'),
('Ben 10 - Protector of Earth', 'An action game featuring Ben 10.', '2007-10-30', 'assets/images/games/ben-10-protector-of-earth.jpg', '1.0');